version: "3"
services:
  dev:
    image: fretlink/purescript-docker:0.12.0

    volumes:
      - .:/home/pureuser/bertrand

    working_dir: /home/pureuser/bertrand
    command: ./watch
    tty: true

  serve:
    build: containers/http
    ports:
      - 9900:9900

    volumes:
      - ./dist:/var/www

    working_dir: /var/www
    command: darkhttpd . --port 9900
