version: "3"
services:
  dev:
    image: fretlink/purescript-docker:0.12.0

    volumes:
      - .:/home/pureuser/bertrand

    working_dir: /home/pureuser/bertrand
    command: ./build
    tty: true

